import undetected_chromedriver as uc
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time
import datetime
import os
import random

# --- إعدادات الرابط ---
TARGET_URL = "https://coursatk.online/years"
OUTPUT_FILE = "index.html"

# --- تصميم المنصة ---
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Academy - المحتوى المفكوك</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {{ --primary: #7c3aed; --bg: #0f172a; --card: #1e293b; --text: #f8fafc; }}
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 0; }}
        
        header {{ background: #111827; padding: 2rem; text-align: center; border-bottom: 4px solid var(--primary); }}
        header h1 {{ margin: 0; font-size: 2.5rem; color: var(--primary); text-transform: uppercase; }}
        header p {{ color: #9ca3af; margin-top: 10px; }}

        .container {{ max-width: 1000px; margin: 2rem auto; padding: 0 1rem; display: flex; flex-direction: column; gap: 20px; }}
        
        .section-title {{ color: #facc15; font-size: 1.5rem; margin-top: 2rem; border-right: 4px solid #facc15; padding-right: 10px; font-weight: bold; }}

        .card {{ background: var(--card); border-radius: 12px; overflow: hidden; border: 1px solid #374151; transition: 0.3s; display: flex; flex-direction: column; }}
        .card:hover {{ transform: translateY(-3px); border-color: var(--primary); }}
        
        .card-body {{ padding: 1.5rem; }}
        .card-title {{ margin: 0 0 10px 0; font-size: 1.1rem; font-weight: bold; color: white; }}
        
        .btn {{ display: inline-flex; align-items: center; gap: 8px; background: var(--primary); color: white; padding: 10px 20px; border-radius: 8px; text-decoration: none; font-weight: 600; margin-top: 10px; }}
        .btn:hover {{ background: #6d28d9; }}
    </style>
</head>
<body>
    <header>
        <h1><i class="fas fa-mask"></i> ACADEMY STEALTH</h1>
        <p>تم اختراق الحماية وسحب المحتوى</p>
        <div style="font-size: 0.8rem; color: #6b7280;">تاريخ العملية: {date}</div>
    </header>

    <div class="container">
        {content}
    </div>
    
    <footer style="text-align: center; padding: 2rem; color: #4b5563;">Generated by Stealth Scraper</footer>
</body>
</html>
"""

def bypass_and_scrape():
    print("🚀 جاري تشغيل المتصفح الشبح (Stealth Mode)...")
    
    # إعدادات التخفي
    options = uc.ChromeOptions()
    options.add_argument('--headless=new')  # وضع التخفي الجديد
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--disable-blink-features=AutomationControlled') # إخفاء علامة الروبوت
    
    # تشغيل المتصفح
    driver = uc.Chrome(options=options, version_main=None)

    try:
        print(f"🕵️‍♂️ جاري التسلل إلى: {TARGET_URL}")
        driver.get(TARGET_URL)
        
        # الانتظار الذكي (مهم جداً عشان صفحة الحماية تختفي)
        print("⏳ جاري الانتظار لعبور بوابة Cloudflare...")
        time.sleep(15)  # انتظار 15 ثانية كاملة
        
        # التحقق هل عدينا ولا لسه؟
        title = driver.title
        print(f"📄 عنوان الصفحة الحالية: {title}")
        
        if "Just a moment" in title or "Cloudflare" in title:
            print("⚠️ الحماية لسه موجودة، هنستنى 10 ثواني كمان...")
            time.sleep(10)
        
        # سحب المحتوى بعد العبور
        page_source = driver.page_source
        soup = BeautifulSoup(page_source, 'html.parser')
        
        html_content = ""
        count = 0
        seen_urls = set()

        # تحليل العناصر (لينكات - صور - فيديوهات)
        # البحث عن كل حاجة ممكنة في الصفحة
        main_body = soup.find('body')
        
        if main_body:
            for element in main_body.find_all(['a', 'h1', 'h2', 'h3', 'video', 'div']):
                
                # العناوين (أسماء المواد أو السنين)
                if element.name in ['h1', 'h2', 'h3'] and element.text.strip():
                    text = element.text.strip()
                    # فلترة العناوين الوهمية
                    if len(text) > 3 and "Cloudflare" not in text:
                         html_content += f'<div class="section-title">{text}</div>'

                # الروابط (الكورسات)
                if element.name == 'a':
                    href = element.get('href')
                    text = element.text.strip()
                    
                    if href and href not in seen_urls and not href.startswith("#"):
                        full_url = urljoin(TARGET_URL, href)
                        
                        # استبعاد روابط كلاود فلير وروابط الموقع نفسه
                        if "cloudflare" in full_url or "coursatk.online" == full_url:
                            continue

                        seen_urls.add(href)
                        count += 1
                        
                        # تحديد نوع الرابط
                        icon = "fa-link"
                        if any(x in full_url for x in ['.pdf', 'drive', 'upload']): icon = "fa-file-arrow-down"
                        if any(x in full_url for x in ['.mp4', 'video', 'watch']): icon = "fa-video"
                        
                        html_content += f"""
                        <div class="card">
                            <div class="card-body">
                                <h3 class="card-title"><i class="fas {icon}"></i> {text if text else 'رابط محتوى'}</h3>
                                <a href="{full_url}" class="btn" target="_blank">فتح / تحميل</a>
                            </div>
                        </div>
                        """
        
        if count == 0:
            html_content = f"""
            <div style='text-align:center; padding:50px; color:#ef4444;'>
                <h3>⚠️ لم نتمكن من العثور على روابط مفيدة.</h3>
                <p>يبدو أن الحماية منعتنا، أو أن الصفحة فارغة.</p>
                <p>عنوان الصفحة التي وصلنا لها: {driver.title}</p>
            </div>
            """

        # الحفظ
        final_html = HTML_TEMPLATE.format(content=html_content, date=datetime.datetime.now())
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write(final_html)
            
        print(f"✅ تمت العملية! تم استخراج {count} عنصر.")

    except Exception as e:
        print(f"❌ حدث خطأ كبير: {e}")
    finally:
        driver.quit()

if __name__ == "__main__":
    bypass_and_scrape()
